### ISSUE TITLE
How can I easily integrate into existing project? Possibility to make a npm package?

### ISSUE THREAD

**Issue by sikandarchishty** [archit-p/editable-react-table#7]
Hey, I have a pretty big project setup already and want to integrate this, now cloning this repo and adding there might overwrite my files. Is there any possibility to make this a **npm package**?

**Comment by archit-p** [comment]
Hi, I hadn’t planned on releasing it on npm as its more of a demo than a library. The API is non-existent, and code is untested. 

My suggestion would be to use this as an inspiration for your own project. The code isn’t really that long and can be easily tweaked to your needs. Let me know if you need help with that!

**Comment by archit-p** [comment]
Hi @sikandarchishty , thanks for the feedback. I've just created #13 to track the transition to a package.
