### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by sundaycrunk** [archit-p/editable-react-table#8]
`npm start
npm ERR! Missing script: "start"`

i might just be an idiot, but there does not seem to be a start script.

**Comment by sundaycrunk** [comment]
proposed npm run dev inside readme

**Comment by archit-p** [comment]
Hi, I noticed this late. I'm actually using the scripts from a vite react starter. Since it had a `dev` script, I just stuck with it instead of the more traditional `start` script we're all used to. Anyways, thanks for checking the project out and good luck exploring!
